@base = http://localhost:5000

POST {{base}}/api/auth/user/verify HTTP/1.1
Content-Type: application/json

{
    "username": "newhere",
    "email": "my@email.com"
}

###
GET {{base}}/db/user/auth?username=Frank&password=bob

###
POST {{base}}/db/user/ HTTP/1.1
Content-Type: application/json

{
    "username": "Frank",
    "password" :"bob"
}